### ISSUE TITLE
1월 8일_필요하다 생각되는 정보들

### ISSUE THREAD

**Issue by kingesay** [Bue-von-hon/Gproject#8]
1. 사람이름 점수(기본적인 정보)
2. 각각 참가했던 대회
3. 각각 풀었던 연습문제(정답/냈지만 오답)

**Comment by Bue-von-hon** [comment]
확실히 2,3번은 어떻게 보여줄지 애매하긴 하네
우선은 거기서 제공하는 그대로를 대부분 보여주고 시간이 남으면 2,3번에 대해 생각해보자
